### ISSUE TITLE
Manuel Open Background Tab

### ISSUE THREAD

**Issue by enesogden** [p2kdev/SafariBlocker#1]
**It is working perfectly but it has a problem. I can not manuel open new background tab. The SafariBlocker menu appears and disappears quickly. No action can be taken for opening background tab.**

- [ ] Device and iOS; iPhone 7 Plus, iOS 14.3

**Comment by daannorris** [comment]
Same here on iPhone X, iOS 13.5

**Comment by p2kdev** [comment]
Should be fixed in v1.2
